### ISSUE TITLE
JBang installed via scoop fails to run

### ISSUE THREAD

**Issue by yostane** [jbangdev/jbang-vscode#111]
Hi,

I have installed JBang using scoop and the JBang command works. However, VScode does not seem to detect it. The error message says that the specified file is not found.

![image](https://github.com/jbangdev/jbang-vscode/assets/1958676/bc4eb4f2-2831-4a21-9e9e-354ef745235f)

`"jbang.home": "C:\\Users\\user\\scoop\\apps\\jbang\\current"`

```pwsh
get-command jbang

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
ExternalScript  jbang.ps1                                                     C:\Users\user\scoop\apps\jbang\current\bin\jbang.ps1
```

JBang-vscode extension version: v0.9.0

```
 code --version
1.84.2
jbang --version
0.113.0
```

BR 😄 ,

**Comment by fbricon** [comment]
can you show the output of 

> dir C:\Users\user\scoop\apps\jbang\current\bin\

**Comment by fbricon** [comment]
I haven't tested with scoop, but I kinda remember chocolatey-installed jbang worked (I'm on a Mac)
Until it's fixed, you can try chocolatey or [manually installed jbang](https://www.jbang.dev/documentation/guide/latest/installation.html#using-jbang)

**Comment by fbricon** [comment]
This was fixed with https://github.com/jbangdev/jbang-eclipse/pull/73

jbang-vscode 0.10.0 was just released to the marketplace, please update.
