### ISSUE TITLE
Unnamed Classes and Instance Main Methods don't show the JBang codelenses

### ISSUE THREAD

**Issue by fbricon** [jbangdev/jbang-vscode#121]
`Run JBang` and `Debug JBang` codelenses are missing from an instance method in an unnamed class:

<img width="601" alt="Screenshot 2024-03-27 at 09 54 27" src="https://github.com/jbangdev/jbang-vscode/assets/148698/552e56dd-fdd9-4ce1-acdd-3453e936ed19">

**Comment by maxandersen** [comment]
with java 23 out...pretty please :) 

```
//JAVA 23+
//PREVIEW 

void main() {
    println("Hello World");
}
```

perfect fine java, but no run jbang option :(

**Comment by fbricon** [comment]
You would also need to wait for vscode-java to provide Java 23 support. Soon ™

**Comment by fbricon** [comment]
![Screenshot 2024-09-19 at 13 13 39](https://github.com/user-attachments/assets/e21c0e7f-2ebd-4407-a4ff-6d1768a31197)
