### ISSUE TITLE
No release version 

### ISSUE THREAD

**Issue by geojaya** [jbangdev/jbang-vscode#19]
When installing on Windows 10 VS code - get this  message prompt - - Can't Install release version of  'jbandev.jbang-vscode' extension because it has no release version

![image](https://user-images.githubusercontent.com/4351259/179680031-2f31784b-7061-4e77-b7d3-6e9b2a7cd0a0.png)

**Comment by fbricon** [comment]
As expected, because it's not mature enough to have a proper release yet. So pre-releases for now only. I won't commit to a release date yet.

**Comment by maxandersen** [comment]
how does one get that error ? I just installed and didnt see errors?

**Comment by fbricon** [comment]
@maxandersen select install release instead of pre-release, on vscode. Vscodium doesn't seem to make a difference between releases and pre-releases

**Comment by fbricon** [comment]
0.2.0 is released on both Microsoft's VS Code Marketplace and open-vsx.org
