### ISSUE TITLE
Incompatible with jbang chocolatey installation

### ISSUE THREAD

**Issue by jeffmaury** [jbangdev/jbang-vscode#38]
I installed jbang through Chocolatey and the extension is not working when opening a JBang script:

![image](https://user-images.githubusercontent.com/695993/201366872-7565a9ac-44aa-4156-b152-04f71448b5e0.png)

Chocolatey installs jbang.exe in the PATH and not jbang.cmd

**Comment by fbricon** [comment]
@maxandersen what's the JBang command that works on all Windows installs?

**Comment by maxandersen** [comment]
You'll need to locate the right one in path. Either jbang.cmd or jbang.exe.

**Comment by fbricon** [comment]
> Downloading jbang
  from 'https://github.com/jbangdev/jbang/releases/download/v0.100.0/jbang-0.100.0.zip'
Progress: 100% - Completed download of C:\Users\fbric\AppData\Local\Temp\chocolatey\jbang\0.100.0\jbang-0.100.0.zip (5 MB).
Download of jbang-0.100.0.zip (5 MB) completed.
Hashes match.
Extracting C:\Users\fbric\AppData\Local\Temp\chocolatey\jbang\0.100.0\jbang-0.100.0.zip to C:\ProgramData\chocolatey\lib\jbang...
C:\ProgramData\chocolatey\lib\jbang
**Added C:\ProgramData\chocolatey\bin\jbang.exe** shim pointed to '..\lib\jbang\jbang-0.100.0\bin\jbang.cmd'.
 The upgrade of jbang was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\jbang'

**Comment by maxandersen** [comment]
yes?
