### ISSUE TITLE
can run/debug jbang show up in the short cut menu?

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang-vscode#45]
would  be awesome if run/debug jbang could show up in the "run" menu/icon 

![2022-12-06_05-54-50](https://user-images.githubusercontent.com/54129/205819349-b32a1128-1a2b-4f53-8534-25d84be39784.png)

**Comment by fbricon** [comment]
@testforstephen @jdneo is there a way to contribute entries there?

**Comment by jdneo** [comment]
Yes: https://github.com/microsoft/vscode-java-debug/blob/b26af9542ee140e10d464c3d75dbf0f6dc3a2e42/package.json#L187-L198

**Comment by fbricon** [comment]
Thanks @jdneo, it worked:
 
![jbang-run-menu](https://user-images.githubusercontent.com/148698/205865511-f8d4941f-4789-44dd-9382-03d7a0cecdaa.gif)
