### ISSUE TITLE
have different icons for run/debug jbang

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang-vscode#51]
would be nice the run/debug jbang icons would be different like run/debug java is different (run button and run button with bug attached)

**Comment by fbricon** [comment]
I tried this CC0 licensed icon, 
[![bug-2-128](https://user-images.githubusercontent.com/148698/213920261-9a39a1bc-ff23-40db-8fa3-f365c3895ff6.png)](https://www.iconsdb.com/green-icons/bug-2-icon.html )
with the JBang one, to get 
![debug-jbang](https://user-images.githubusercontent.com/148698/213920337-83c3dc57-818a-44e6-b88f-2d055c832e24.png)

Which renders like this:
 
<img width="386" alt="Screenshot 2023-01-22 at 15 07 22" src="https://user-images.githubusercontent.com/148698/213920199-a4e73dc0-3d35-4e1f-b3c5-0d7aa763787e.png">
<img width="381" alt="Screenshot 2023-01-22 at 15 08 42" src="https://user-images.githubusercontent.com/148698/213920200-3f47aaf6-f583-42a9-af9e-2fa8a2a3c779.png">
<img width="380" alt="Screenshot 2023-01-22 at 15 09 02" src="https://user-images.githubusercontent.com/148698/213920201-25460098-2e1d-4e55-9264-137666534db3.png">
<img width="383" alt="Screenshot 2023-01-22 at 15 09 28" src="https://user-images.githubusercontent.com/148698/213920202-9e0c2f2e-5a6a-43ce-a752-178b299709d0.png">

Not a greeeaaat combo, especially in dark mode. You can tell I'm no @insectengine. But it's different, as requested ;-)

@maxandersen let me know if you can live with it or feel free to provide a better icon

**Comment by maxandersen** [comment]
Better than what er have now so +1 and lets See if @insectengine or other might suggest something in future.
