### ISSUE TITLE
NullPointerException during "Updating workspace folders"

### ISSUE THREAD

**Issue by yeroc** [jbangdev/jbang-vscode#70]
After migrating file to a new machine I got these errors in the output console in VS Code after adding the folder containing jbang scripts to my workspace:

```
[Error - 10:01:02 AM] May 25, 2023, 10:01:02 AM An internal error occurred during: "Updating workspace folders".
Cannot invoke "java.util.Collection.stream()" because "triggerFiles" is null
java.lang.NullPointerException: Cannot invoke "java.util.Collection.stream()" because "triggerFiles" is null
	at dev.jbang.eclipse.ls.internal.JBangImporter.applies(JBangImporter.java:46)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:149)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager$2.runInWorkspace(ProjectsManager.java:252)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I can't tell whether this was fatal.  After a period of time it seemed to resolve itself.  Not sure if it was because the Java tooling was still initializing or not?

VS Code Version Info:  

Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T15:00:40.428Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

JBang Extension Version: v0.6.0

Note that while my local machine is running Mac OSX, I'm using the Remote development extensions to connect to a remote Linux (AlmaLinux 8) host where the jbang scripts/code resides.

**Comment by fbricon** [comment]
TBH remote development is not something that I have tried. So I wouldn't be surprised if it doesn't work. Fixing the NPE is trivial, but beyond that, I can't guarantee it'll work in that scenario without spending some time setting up such remote dev environment.
